### PR TITLE
fix memory manager result bug

### LINKED ISSUE #1939: [BUG] Invalid Pointer Dereference due to std::vector auto-resizing in Memory Manager Result push_back
**Describe the bug**
When a `Memory Manager` class is registered, the results of each iteration are appended to an std::vector, and a pointer to the newly added element is used as a reference thereafter.
https://github.com/google/benchmark/blob/8d4fdd6e6e003867045e0bb3473b5b423818e4b7/src/benchmark_runner.cc#L434-L435

However, when the vector automatically resizes, these pointers become invalid, leading to corrupted statistical measurements.
The problem only occurs if the number of repetitions is greater than one.

**To reproduce**
1. Register a `Memory Manager` class 
2. Run any benchmark with at least 3 repetitions
3. User the Json reporter to see the corrupted memory related stats.

**Expected behavior**
Pointers to stored values should remain valid, or the implementation should ensure they are updated correctly when the vector reallocates.

**Additional context**
Possible fixes:
- Use `std::list` or instead of `std::vector` to avoid reallocation issues.
- Store indices instead of pointers if possible.
- Reserve `GetNumRepeats()` values to the `std::vector` to ensure no automatic growth is performed.

### PR DESCRIPTION
**Pull request by EfesX**
Fixes #1939

### CODE REVIEW

File: src/benchmark_runner.cc [hunk 1]
```diff
@@ -508,13 +504,14 @@ void BenchmarkRunner::DoOneRepetition() {
   }
 
   // Produce memory measurements if requested.
-  MemoryManager::Result* memory_result = nullptr;
+  MemoryManager::Result memory_result;
   IterationCount memory_iterations = 0;
   if (memory_manager != nullptr) {
     // Only run a few iterations to reduce the impact of one-time
     // allocations in benchmarks that are not properly managed.
     memory_iterations = std::min<IterationCount>(16, iters);
```
Comment (LebedevRI) [inline src/benchmark_runner.cc:512]: I would propose to change `(bool)memory_result.is_valid` with `memory_iterations > 0`.

Comment (EfesX) [reply src/benchmark_runner.cc]: I put `memory_iteration` in `MemoryManager::Result` to use it in `JSONReporter::PrintRunData`

File: include/benchmark/benchmark.h [hunk 2]
```diff
@@ -306,6 +306,8 @@ namespace benchmark {
 class BenchmarkReporter;
 class State;
 
+typedef int64_t IterationCount;
```
Comment (LebedevRI) [inline include/benchmark/benchmark.h:309]: `using IterationCount = int64_t`

File: src/json_reporter.cc [hunk 3]
```diff
@@ -306,8 +306,8 @@ void JSONReporter::PrintRunData(Run const& run) {
     out << ",\n" << indent << FormatKV(c.first, c.second);
   }
 
-  if (run.memory_result != nullptr) {
-    const MemoryManager::Result memory_result = *run.memory_result;
+  if (run.memory_result.memory_iterations > 0) {
+    const MemoryManager::Result& memory_result{run.memory_result};
```
Comment (LebedevRI) [inline src/json_reporter.cc:310]: `    const MemoryManager::Result& memory_result = run.memory_result;`

**Comment by LebedevRI** [comment]
Yep, something like this should work i suppose.

File: include/benchmark/benchmark.h [hunk 4]
```diff
@@ -410,6 +413,8 @@ class MemoryManager {
     // ie., total_allocated_bytes - total_deallocated_bytes.
     // Init'ed to TombstoneValue if metric not available.
     int64_t net_heap_growth;
+
+    IterationCount memory_iterations;
```
Comment (LebedevRI) [inline include/benchmark/benchmark.h:417]: Ah, i thought we already had `memory_iterations` in `Run`, but apparently not.

File: test/memory_results_gtest.cc [hunk 5]
```diff
@@ -0,0 +1,101 @@
+#include <vector>
+
```
Comment (LebedevRI) [inline test/memory_results_gtest.cc:2]: Just to check: you have verified that this test fails on its own, without the fix, correct?

Comment (EfesX) [reply test/memory_results_gtest.cc:2]: Of course. I was able to confirm and reproduce the issue in this test initially.

After that, when I fixed the issue, the test had to be changed slightly.

**Comment by LebedevRI** [comment]
Looks like more casts are needed  :)

File: test/memory_results_gtest.cc [hunk 6]
```diff
@@ -0,0 +1,101 @@
...
+TEST_F(MemoryResultsTest, ResultsTest) {
+  counts::reset();
+  MemoryManager* mm = new TestMemoryManager;
+  RegisterMemoryManager(mm);
+
+  RunSpecifiedBenchmarks(&reporter);
+  EXPECT_EQ(reporter.store.size(), N_REPETITIONS);
+
+  for (int64_t i = 0; i < static_cast<int64_t>(reporter.store.size()); i++) {
```
Comment (dmah42) [inline test/memory_results_gtest.cc:93]: i suspect having `i` be size_t might be the way to go here.

**Comment by LebedevRI** [comment]
Hmm, those msvc failure look weird. I don't think this PR can cause them.

**Comment by EfesX** [comment]
> Hmm, those msvc failure look weird. I don't think this PR can cause them.

I reproduced the failure on my Windows computer. I don’t understand why, but it seems like the failure is caused by my PR. 

e1eaa52 might resolve the issue.

File: test/memory_results_gtest.cc [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+
+using benchmark::ClearRegisteredBenchmarks;
+using benchmark::ConsoleReporter;
+using benchmark::MemoryManager;
+using benchmark::RegisterBenchmark;
+using benchmark::RunSpecifiedBenchmarks;
+using benchmark::State;
+using benchmark::internal::Benchmark;
+
+namespace counts {
```
Comment (dmah42) [inline test/memory_results_gtest.cc:18]: this would also work as an unnamed namespace, fyi.

File: test/memory_results_gtest.cc [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+};
+
+TEST_F(MemoryResultsTest, NoMMTest) {
+  RunSpecifiedBenchmarks(&reporter);
+  EXPECT_EQ(reporter.store.size(), 0);
+}
+
+TEST_F(MemoryResultsTest, ResultsTest) {
+  counts::reset();
+  MemoryManager* mm = new TestMemoryManager;
```
Comment (dmah42) [inline test/memory_results_gtest.cc:87]: auto mm = std::make_unique<TestMemoryManager>();

at the very least you want () after `TestMemoryManager`.

**Review by LebedevRI — APPROVED** [review]

**Comment by LebedevRI** [comment]
@EfesX thank you!
