### PR TITLE
fix: added benchmark_counters_tabular for file

### LINKED ISSUE #834: --benchmark_counters_tabular is invalid for --benchmark_out
when set --benchmark_counters_tabular=true and --benchmark_output_format=console，It does not take effect on the output file. The output file still looks like:
```
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------
l4cp_a_c/32/manual_time      3349447 ns        74761 ns          209 flush=0.68267 items_per_second=298.557/s
l4cp_a_c/512/manual_time    20886315 ns        0.000 ns           34 flush=0.707233 items_per_second=47.8782/s
l4cp_a_f/32/manual_time        62964 ns        45752 ns        10587 flush=0.0637161 items_per_second=15.8821k/s
l4cp_a_f/512/manual_time      182277 ns        50457 ns         3716 flush=0.216913 items_per_second=5.48616k/s
```

### PR DESCRIPTION
**Pull request by varshneydevansh**
## The basics

- [x] I branched from main
- [x] My pull request is against main
- [x] My code follows the Google Style Guide
- [x] I ran `clang-format`

### Resolves

- Fixes #834 

### Proposed Changes

`--benchmark_counters_tabular=true` flag should be correctly applied for the output files for the `--benchmark_out_format=console`

#### Behavior Before Change

```sh
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------
l4cp_a_c/32/manual_time      3349447 ns        74761 ns          209 flush=0.68267 items_per_second=298.557/s
l4cp_a_c/512/manual_time    20886315 ns        0.000 ns           34 flush=0.707233 items_per_second=47.8782/s
l4cp_a_f/32/manual_time        62964 ns        45752 ns        10587 flush=0.0637161 items_per_second=15.8821k/s
l4cp_a_f/512/manual_time      182277 ns        50457 ns         3716 flush=0.216913 items_per_second=5.48616k/s
```

#### Behavior After Change

```sh
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations     flush  items_per_second
------------------------------------------------------------------------------------
l4cp_a_c/32/manual_time      3349447 ns        74761 ns          209   0.68267         298.557/s
l4cp_a_c/512/manual_time    20886315 ns        0.000 ns           34  0.707233         47.8782/s
l4cp_a_f/32/manual_time        62964 ns        45752 ns        10587 0.0637161        15.8821k/s
l4cp_a_f/512/manual_time      182277 ns        50457 ns         3716  0.216913        5.48616k/s
```

### Reason for Changes

With the latest version, the below `command line` should be applied to the `output file` for the `console` option for a clear output.

```sh
$ ./bm --benchmark_out=result.txt --benchmark_out_format=console
--benchmark_counters_tabular=true
```

### Test Coverage

I haven't tested this, as soon as I got confirmation that these are the required changes that will update the status of the Test Coverage.

### Documentation

I do not think there is any need for the documentation changes/ update as it's a bug which is correcting the output for the files.

### CODE REVIEW

File: src/benchmark.cc [hunk 1]
```diff
@@ -574,8 +574,14 @@ size_t RunSpecifiedBenchmarks(BenchmarkReporter* display_reporter,
       std::exit(1);
     }
     if (!file_reporter) {
-      default_file_reporter = internal::CreateReporter(
-          FLAGS_benchmark_out_format, ConsoleReporter::OO_None);
+      if (FLAGS_benchmark_out_format == "console" &&
```
Comment (dmah42) [inline src/benchmark.cc:577]: why only for console?  i think we should instead just check for the _tabular flag and pass the result to the `CreateReporter` call.

Comment (varshneydevansh) [reply src/benchmark.cc:577]: That's what I thought afterward, but I considered changing it after feedback. Doing it.

**Review by dmah42 — APPROVED** [review]

**Comment by dmah42** [comment]
amazing. thank you!
