### PR TITLE
Fix type conversion warnings.

### LINKED ISSUE #949: Warnings C4244 and C4305 'argument': truncation / conversion from 'double' to 'RawType' / 'const M' to 'const Element'
compiled with Visual Studio 2019 Professional 16.5.1 on windows 10 1903.

`\src\benchmark_runner.cc(267,13): warning C4244: 'initializing': conversion from 'double' to 'benchmark::IterationCount', possible loss of data
\src\benchmark_runner.cc(266,41): warning C4244: 'initializing': conversion from 'double' to 'const benchmark::IterationCount', possible loss of data
\test\statistics_gtest.cc(25,1): warning C4305: 'argument': truncation from 'double' to 'RawType' \test\statistics_gtest.cc(24,1): warning C4244: 'argument': conversion from 'double' to 'RawType', possible loss of data
\test\../src/benchmark_register.h(25,1): warning C4244: '*=': conversion from 'int' to 'T', possible loss of data
\src\googlemock\include\gmock/gmock-matchers.h(368,12): warning C4244: 'argument': conversion from 'const M' to 'const Element', possible loss of data

### PR DESCRIPTION
**Pull request by dominichamon**
Fixes #949

Tested locally (Linux/clang), but warnings are on MSVC so may differ.

### CODE REVIEW

File: test/statistics_gtest.cc [hunk 1]
```diff
@@ -21,8 +21,8 @@ TEST(StatisticsTest, Median) {
 TEST(StatisticsTest, StdDev) {
   EXPECT_DOUBLE_EQ(benchmark::StatisticsStdDev({101, 101, 101, 101}), 0.0);
   EXPECT_DOUBLE_EQ(benchmark::StatisticsStdDev({1, 2, 3}), 1.0);
-  EXPECT_FLOAT_EQ(benchmark::StatisticsStdDev({1.5, 2.4, 3.3, 4.2, 5.1}),
-                  1.42302495);
+  EXPECT_DOUBLE_EQ(benchmark::StatisticsStdDev({2.5, 2.4, 3.3, 4.2, 5.1}),
+                   1.1510864433221342);
```
Comment (LebedevRI) [inline test/statistics_gtest.cc:25]: https://travis-ci.org/github/google/benchmark/jobs/668673797 says it's `1.1510864433221341`
Since everything else doesn't agree, i guess this is fast-math discrepancy.
But i also guess this only happened to work before due to the numbers chosen.
Can you use `EXPECT_NEAR()` instead?

Comment (dominichamon) [reply test/statistics_gtest.cc]: no need to, i just need to drop the last digit. `EXPECT_DOUBLE_EQ` already checks for within 4 ULP.

Comment (LebedevRI) [reply test/statistics_gtest.cc]: If that works, sure.
